service: eventbridge-serverless-demo
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: sagar
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: '*'

functions:
  publishEvent:
    handler: handler.publishEvent
    events:
      - http:
          path: publishEvent
          method: post

  consumeEvent:
    handler: handler.consumeEvent
    events:
      - eventBridge:
          name: publisherConsumerRule
          pattern:
            source:
              - my-source